name: workflow-1

on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-24.04
    steps:
      - name: print a msg
        run: echo "GitHub Actions workflow has started!"

      - name: Print second msg
        run: echo "Workflow step executed successfully!"
