name: workflow-1

on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        run: actions/checkout@v7

      - name: install dependencies
        run: npm install
        
      - name: test
        run: npm test

      - name: start the app
        run: npm start
