name: Event Triggers and Job Flow

on:
  push:
    branches: [ "main" ]
    paths: [ "src/**" ] 
  workflow_dispatch: 

jobs:

  job-1-build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building the app... takes 10 seconds." && sleep 10

  job-2-lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Linting the code... takes 5 seconds." && sleep 5

  job-3-deploy:
    needs: [job-1-build, job-2-lint]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying only because build and lint succeeded!"
