name: Workflow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  print-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Print First Message
        run: echo "Message 1: Hello from GitHub Actions!"

      - name: Print Second Message
        run: echo "Message 2: Workflow executed successfully!"
